version: 2.1

orbs:
  python: circleci/python@2.1.1
  coveralls: coveralls/coveralls@1.0.6

workflows:
  testing:
    jobs:
      - build-and-test-3-10
      - build-and-test-3-7
      - coveralls-build
      - black-format-check

jobs:
  coveralls-build:
    docker:
      - image: cimg/python:3.10-node
    steps:
      - checkout
      - run:
          name: Install and run coverage tests
          command: 'pip install -r dev-requirements.txt && coverage run -a --source=gwbackupy setup.py test && coverage run -a -m pytest gwbackupy && coverage-lcov && echo 1'
      - coveralls/upload:
          path_to_lcov: lcov.info
  build-and-test-3-10:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - python/install-packages:
          pip-dependency-file: dev-requirements.txt
          pkg-manager: pip
      - run:
          name: Run tests 3.10
          command: pytest
  build-and-test-3-7:
    docker:
      - image: cimg/python:3.7
    steps:
      - checkout
      - python/install-packages:
          pip-dependency-file: dev-requirements.txt
          pkg-manager: pip
      - run:
          name: Run tests 3.7
          command: pytest
  black-format-check:
    docker:
      - image: cimg/python:3.10.5
    steps:
      - checkout
      - run:
          name: Check black format
          command: |
            pip install -U black
            python -m black --check setup.py gwbackupy
