version: 2.1

orbs:
  python: circleci/python@2.1.1
  coveralls: coveralls/coveralls@1.0.6

workflows:
  testing:
    jobs:
      - build-and-test
      - coveralls-build

jobs:
  coveralls-build:
    docker:
      - image: cimg/python:3.10-node
    steps:
      - checkout
      - run:
          name: Install and run coverage tests
          command: 'pip install -r requirements.txt && coverage run -a --source=gwbackupy setup.py test && coverage run -a -m pytest gwbackupy && coverage-lcov && echo 1'
      - coveralls/upload:
          path_to_lcov: lcov.info
  build-and-test:
    docker:
      - image: cimg/python:3.10.5
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: pytest