name: Pytest

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
      - 'CONTRIBUTING.md'
      - 'LICENSE'
      - '.github/**'
      - '.gitignore'
      - 'SECURITY.md'

jobs:
  pytest:
    strategy:
      matrix:
        python-version: [3.9, 3.13]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: pip install -r dev-requirements.txt

      - name: Run pytest
        run: pytest
